/**:
    ros__parameters:
        use_sim_time: false
        odom_topic: "/aft_mapped_to_init"
        cloud_topic: "/cloud_registered"
        map_frame: "map"
        odom_frame: "camera_init"

        keyframe:
            min_dist: 0.5
            min_angle_deg: 8.0
            min_time: 0.5
            max_count: 2000

        cloud:
            voxel_size: 0.25
            min_points: 80

        init:
            enabled: true
            accumulate_frames: 3
            voxel_size: 0.20
            local_radius: 15.0
            icp_max_corr: 1.5
            icp_max_iter: 40
            fitness_max: 0.60
            coarse_max_iter: 3
            fine_max_iter: 15
            valid_ratio_min: 0.65
            plane_dist: 0.10
            prior_T: [0.0, 0.0, 0.0]
            xy_range: [-0.5, 0.25, 0.5]
            yaw_range: [-0.3, 0.1, 0.3]

        prior:
            enabled: true
            map_path: "/home/dtc/robo_sys/clean_map.pcd"
            map_voxel_size: 0.30
            local_radius: 15.0
            icp_max_corr: 1.0
            icp_max_iter: 30
            fitness_max: 0.30
            add_every_n_keyframes: 3
            noise_xyz: 0.20
            noise_rpy: 0.10

        loop:
            enabled: true
            min_separation: 30
            search_radius: 2.0
            icp_max_corr: 1.0
            icp_max_iter: 30
            fitness_max: 0.20
            add_every_n_keyframes: 5
            noise_xyz: 0.15
            noise_rpy: 0.08
